// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaMedico.Entities.Entities
{
    public partial class tbEnfermedadesPorPersona
    {
        public int EnPe_Id { get; set; }
        public int Enfe_Id { get; set; }
        public string Pers_Identidad { get; set; }
        public bool? EnPe_Estado { get; set; }
        public int EnPe_Creacion { get; set; }
        public DateTime EnPe_FechaCreacion { get; set; }
        public int? EnPe_Modificacion { get; set; }
        public DateTime? EnPe_FechaModificacion { get; set; }
        [NotMapped]
        public string Creacion { get; set; }
        [NotMapped]
        public string Modificacion { get; set; }
        public virtual tbUsuarios EnPe_CreacionNavigation { get; set; }
        public virtual tbUsuarios EnPe_ModificacionNavigation { get; set; }
        public virtual tbEnfermedades Enfe { get; set; }
        public virtual tbPersonas Pers_IdentidadNavigation { get; set; }
    }
}